### ISSUE TITLE
Satellite API giving response with unidentified Data type

### ISSUE THREAD

**Issue by Aishwarya-modi95** [Animesh-Samanta/FA1#1]
Hi, Animesh satellite responded with unidentified Data type we cannot identify
its int long flat or double please intervene in this case to find the valley in the received matrix.

**Comment by Aishwarya-modi95** [comment]
Its having JSON pay load don't try to read at client side better do it at server side it will be easy.

**Comment by Animesh-Samanta** [comment]
Hi,Aish
Its having JSON pay load don't try to read at client side better do it at server side it will be easy.
